# Generated by Django 5.0.7 on 2024-07-31 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('system', 'SYSTEM'), ('user', 'USER'), ('assistant', 'ASSISTANT')], max_length=20)),
                ('model_used', models.CharField(blank=True, choices=[('gpt-3.5-turbo', 'GPT_3_5_TURBO'), ('gpt-4-1106-preview', 'GPT_4'), ('gpt-4o-2024-05-13', 'GPT_4_O'), ('llama3:8b-instruct-q8_0', 'LAMA3_8B')], max_length=255, null=True)),
                ('predicted_semantic', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(default=dict)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.chat')),
            ],
        ),
    ]
