# Generated by Django 5.0.7 on 2024-08-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_chat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='predicted_semantic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
