# Generated by Django 5.0.7 on 2024-08-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_message_predicted_semantic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='model_used',
            field=models.CharField(blank=True, choices=[('gpt-3.5-turbo', 'GPT_3_5_TURBO'), ('gpt-4-1106-preview', 'GPT_4'), ('gpt-4o-2024-05-13', 'GPT_4_O'), ('llama3:8b-instruct-q8_0', 'LLAMA3_8B')], max_length=255, null=True),
        ),
    ]
